repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: py-compile
        name: python -m py_compile
        entry: python -m py_compile
        language: system
        types: [python]
