repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: [--fix, .]
        pass_filenames: false
      - id: ruff-format
        args: [.]
        pass_filenames: false
  - repo: local
    hooks:
      - id: py-compile
        name: python -m py_compile
        entry: python -m py_compile server.py
        language: system
        pass_filenames: false
